### ISSUE TITLE
Qt6 Upgrade

### ISSUE THREAD

**Issue by dail8859** [flathub/com.github.dail8859.NotepadNext#11]
The next release of Notepad Next (at some point) will use Qt6.4.1

What exactly needs done to the yml file to switch Qt versions?

**Comment by zocker-160** [comment]
You just need to update the runtime version to 6.x (currently the latest version available is 6.4).

But I would recommend against it unless absolutely needed, as it will break theming on all distros as they all still use QT5 (5.15.7 for Arch and 5.15.3 for Ubuntu)

**Comment by dail8859** [comment]
> But I would recommend against it unless absolutely needed, as it will break theming on all distros as they all still use QT5

Any idea when Qt6 will be supported? I'd like to move to Qt6.

**Comment by zocker-160** [comment]
> Any idea when Qt6 will be supported? I'd like to move to Qt6.

It is supported already, as in "it will run and work", but expect bug reports from users wondering why it suddenly ignores system theming.

KDE will need to move to QT6 for full support which currently does not even have a schedule for release, so I would guess that it is at least one year away.

**Comment by dail8859** [comment]
That is unfortunate to hear but appreciate the info.

The problem with supporting so many systems is you have to stick with the least common denominator. Guess I'll have to decide what to do.

**Comment by dail8859** [comment]
I think for now I'll keep the flatpak version on 5.15. Everything else will move to 6.4 since there's some issues fixed for Windows and MacOS. If for some reason people have issues with the 6.4 AppImage then I can also release a secondary AppImage on 5.15.

As long as the code continues to build with 5.15 and 6.4 I think there shouldn't be any major issues. If 5.15 starts to be a burden then I'll make a decision then, but hopefully that's closer to the point KDE supports Qt6.

Thanks for your input as always!

**Comment by zocker-160** [comment]
I can offer you to push a QT 6.4 build to flathub-beta, so we can test to see how it looks / works.

If supporting 5.15 becomes a blocker, it is easy to switch the branches from beta to stable.

**Comment by zocker-160** [comment]
I just noticed, that we already have a beta build available for Notepad Next, I will push an update to rebuild with 6.4 and see what happens.

**Comment by dail8859** [comment]
> If supporting 5.15 becomes a blocker, it is easy to switch the branches from beta to stable.

Great idea!
