### ISSUE TITLE
Qt6+?

### ISSUE THREAD

**Issue by dail8859** [flathub/com.github.dail8859.NotepadNext#19]
@zocker-160

A long, long time ago (well...it feels like a long time ago) we stuck with Qt5.15:

https://github.com/flathub/com.github.dail8859.NotepadNext/pull/12#issuecomment-1410972944

Any reason to still stick with that? Is there "better" support for Qt6.5, or something at least Qt6+?

**Comment by zocker-160** [comment]
So a few things have changed since back then. Most importantly KDE 6 has released a month ago which is based on QT6. 

The only problem with this currently is, that because it only released one month ago, it is currently not shipping to many distros apart from the most bleeding edge ones like Arch.

That being said, the problem with the themes _should_ be gone, but only testing can confirm that.

I have updated Qt runtime to 6.6 on the beta branch to do some testing.

**Comment by zocker-160** [comment]
What Qt version would you like to have? The newest I can offer you is 6.6.

**Comment by dail8859** [comment]
> What Qt version would you like to have? The newest I can offer you is 6.6.

I've been using 6.5 for all the official releases for other platforms. Normally I'm trying to stick with LTS versions (though since I use the open source version, I guess that doesn't really gain me anything lol)

So 6.5 would be my preference if possible.

**Comment by zocker-160** [comment]
Ok so here are my results:

With 6.5 everything seems to be working, although theming is kinda broken, the colors are correct, although the rest of the theme is not.
With 6.6 the theme works as expected and users won't see a difference.

6.5:
![Screenshot_20240412_134010](https://github.com/flathub/com.github.dail8859.NotepadNext/assets/36563538/61875e14-be01-4113-bbca-6ee2d606be41)

6.6: (notice the ok button is correct here)
![Screenshot_20240412_134340](https://github.com/flathub/com.github.dail8859.NotepadNext/assets/36563538/93e55d0d-60f9-44db-9a62-beb6de1ac38c)

old 5.15:
![Screenshot_20240412_134721](https://github.com/flathub/com.github.dail8859.NotepadNext/assets/36563538/17eaefbc-9b21-4752-b6c1-f113ff94c075)

Your call.

**Comment by dail8859** [comment]
For the sake of trying to the Qt version the same across platforms, let's go with 6.5

If there are any major complaints, then we can probably safely bump it to 6.6 in the future.

**Comment by zocker-160** [comment]
done

**Comment by dail8859** [comment]
Awesome. Thanks so much for your help!
