### ISSUE TITLE
Enable wayland socket by default

### ISSUE THREAD

**Issue by ghost** [flathub/com.github.dail8859.NotepadNext#2]
This is just a small enhancement. I have noticed that `QT_QPA_PLATFORM` is set to `xcb` by default on the Flatpak image. The wayland socket is disabled by default as well, even though the application seems to support Wayland just fine which I have confirmed by setting QT_QPA_PLATFORM=wayland and enabling the wayland socket manually.
![image](https://user-images.githubusercontent.com/15093096/164186017-a7406803-27ac-4d3e-8bbb-247b463bd89d.png)

**Comment by zocker-160** [comment]
X11 was chosen because all the testing for the Flatpak was made on X11, so I wanted to make sure I upload a version to Flathub that works 100%.

I will create a beta branch with wayland enabled so ppl can give feedback. If there are no issues, I will make it the default.

**Comment by zocker-160** [comment]
Wayland build based on v0.5 is now available in flathub-beta.

Please let me know if there are any issue.

**Comment by ghost** [comment]
So far I have noticed that the "Open file" dialog is not opening up, but that might be due to having portals misconfigured on my end. I will keep testing.
