### ISSUE TITLE
Single Application Support

### ISSUE THREAD

**Issue by dail8859** [flathub/com.github.dail8859.NotepadNext#27]
Per https://github.com/itay-grudev/SingleApplication/issues/199 it sounds like for the application to enforce a single instance it needs to use `--device=shm`. Can someone confirm that single instance is not working for the flatpak and if so `--device=shm` can be added.

**Comment by zocker-160** [comment]
I just tried it and it works without `--device=shm`:

![image](https://github.com/user-attachments/assets/8305a61d-f769-4395-ae36-c6746a1ca437)

**Comment by dail8859** [comment]
Well that's definitely good news then. Per the linked conversation I figured it wouldn't work but obviously it does. Thanks for testing!
