### ISSUE TITLE
Add `text/plain` MIME type to desktop entry

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.github.dail8859.NotepadNext#3]
At the moment, I am unable to open files from an "Open With" dialog.

Commit https://github.com/dail8859/NotepadNext/commit/3477b35e484376c0bfa3331c7f8d1dc5305b39b5 adds the necessary MIME type support to open files from a dialog. I suggest to create a new release with this patch included, or patch the app with this commit.

**Comment by zocker-160** [comment]
please use the beta version you can find on flathub-beta, it does include this patch.

**Comment by TheEvilSkeleton** [comment]
Can I submit a PR for the stable branch to add the patch? I don't think we should force users to use the beta branch just to make software convenient.

**Comment by zocker-160** [comment]
I am not the dev, so I cannot create any new version tags. I want stable to always be the latest tag and not newer.

maybe @dail8859 can create a new stable tag for us (like v5.0.1) or something like that

**Comment by TheEvilSkeleton** [comment]
That's fair. Is it possible if we can patch this package to include the MIME type?

**Comment by zocker-160** [comment]
> That's fair. Is it possible if we can patch this package to include the MIME type?

yes I can if  @dail8859  decides to not create a new tag anytime soon.

**Comment by dail8859** [comment]
I was going to wait a bit to do a release, but since there's been some small quality-of-life type of improvements then a minor release is probably a good idea. I'll try to get a new release out in the next few days if my schedule permits.

**Comment by dail8859** [comment]
v0.5.1 has been released.

[9d19014e770b5c04c634e233f8d413ec631c1646](https://github.com/dail8859/NotepadNext/commit/9d19014e770b5c04c634e233f8d413ec631c1646)

**Comment by TheEvilSkeleton** [comment]
Thanks! I opened https://github.com/flathub/com.github.dail8859.NotepadNext/pull/4.
